title:            PBDL
description:      "Physics-based Deep Learning"
logo:             logo.png
disqus_shortname: PBDL
share:            true
dropcap:          true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  "thunil.github.io"

# Owner/author information
owner:
  name:           TUM I15
  avatar:         i15ge.jpg
  email:          i15ge@cs.tum.de
  description:    Physics-based Deep Learning - Artificial Neural Networks for Physical Problems
  # Social networking links used in footer. Update and remove as you like.
  twitter:        thuereygroup
  github:         thunil      

# Analytics and webmaster tools stuff goes here
google_analytics:  
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: Imprint
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers: 
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://thunil.github.io/'
  relativeLinks: 'http://thunil.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Title!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Fluid Simulation"
              value: fluidsimulation
            - name: "Single-phase Simulation"
              value: singlephasesimulation
            - name: "Liquid Simulation"
              value: liquidsimulation
            - name: "Fluid Simulation"
              value: fluidsimulation
            - name: "Navier-Stokes"
              value: Navier-Stokes
            - name: "Physics-based Deep Learning"
              value: physicsbaseddeeplearning
            - name: "Deep Learning in General"
              value: deeplearninggeneral
            - name: "Deformable Body Simulation"
              value: deformablebodysimulation
            - name: "RNNs"
              value: rnns
            - name: "ConvNets"
              value: convnets
            - name: "GANs"
              value: gans
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
